"""Source-only MixStyle augmentation for cross-subject domain generalization.

The helpers in this module implement a feature-space variant of MixStyle for
M/EEG transfer experiments.  Synthetic source rows are generated by replacing a
trial's source-domain style statistics with a convex mixture of its own domain
statistics and another source domain's statistics.  Labels are copied from the
source row; held-out target features and target labels are intentionally absent
from the public API.
"""

from __future__ import annotations

from collections.abc import Hashable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

import numpy as np

SOURCE_MIXSTYLE_PROTOCOL = "source_only_mixstyle_domain_generalization"
SOURCE_MIXSTYLE_CATEGORY = "1_strict_source_only"
DEFAULT_MIXSTYLE_ALPHA = 0.3
DEFAULT_MIXSTYLE_MIXES_PER_ROW = 1
DEFAULT_MIXSTYLE_STYLE_STRENGTH = 1.0
DEFAULT_MIXSTYLE_SYNTHETIC_WEIGHT = 1.0
_MIN_SCALE = 1e-12


@dataclass(frozen=True, slots=True)
class SourceMixStyleConfig:
    """Configuration for source-only feature-space MixStyle augmentation."""

    mixes_per_row: int = DEFAULT_MIXSTYLE_MIXES_PER_ROW
    alpha: float = DEFAULT_MIXSTYLE_ALPHA
    style_strength: float = DEFAULT_MIXSTYLE_STYLE_STRENGTH
    synthetic_weight: float = DEFAULT_MIXSTYLE_SYNTHETIC_WEIGHT
    include_original: bool = True
    random_state: int | None = 13


@dataclass(frozen=True, slots=True)
class SourceMixStyleResult:
    """Augmented source features, labels, weights, and provenance."""

    features: np.ndarray
    labels: np.ndarray
    sample_weight: np.ndarray
    domain_ids: np.ndarray
    synthetic_mask: np.ndarray
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def n_original(self) -> int:
        """Number of original rows retained in the output."""

        return int(np.count_nonzero(~self.synthetic_mask))

    @property
    def n_synthetic(self) -> int:
        """Number of synthetic rows appended to the output."""

        return int(np.count_nonzero(self.synthetic_mask))


@dataclass(frozen=True, slots=True)
class _DomainStyleStats:
    domain_id: Hashable
    mean: np.ndarray
    scale: np.ndarray
    n_rows: int


def source_mixstyle_config(
    *,
    mixes_per_row: int | str = DEFAULT_MIXSTYLE_MIXES_PER_ROW,
    alpha: float | str = DEFAULT_MIXSTYLE_ALPHA,
    style_strength: float | str = DEFAULT_MIXSTYLE_STYLE_STRENGTH,
    synthetic_weight: float | str = DEFAULT_MIXSTYLE_SYNTHETIC_WEIGHT,
    include_original: bool = True,
    random_state: int | str | None = 13,
) -> SourceMixStyleConfig:
    """Normalize user-facing MixStyle augmentation options."""

    return SourceMixStyleConfig(
        mixes_per_row=_normalize_nonnegative_int(mixes_per_row, name="mixes_per_row"),
        alpha=_normalize_positive_float(alpha, name="alpha"),
        style_strength=_normalize_unit_interval(style_strength, name="style_strength"),
        synthetic_weight=_normalize_nonnegative_float(synthetic_weight, name="synthetic_weight"),
        include_original=bool(include_original),
        random_state=None if random_state in {None, "", "none", "None"} else _normalize_nonnegative_int(random_state, name="random_state"),
    )


def augment_source_domains_mixstyle(
    source_features: Sequence[Sequence[float]] | np.ndarray,
    source_labels: Sequence[Any] | np.ndarray,
    source_domains: Sequence[Hashable] | np.ndarray,
    *,
    config: SourceMixStyleConfig | Mapping[str, Any] | None = None,
) -> SourceMixStyleResult:
    """Return source-only MixStyle-augmented feature rows.

    Parameters
    ----------
    source_features:
        Source feature rows pooled across source subjects or source domains.
    source_labels:
        One source label per feature row.  Labels are copied to synthetic rows.
    source_domains:
        One source-domain identifier per feature row, typically the source subject.
    config:
        MixStyle configuration.  A mapping is normalized through
        :func:`source_mixstyle_config`.

    Returns
    -------
    SourceMixStyleResult
        Augmented source rows, copied labels, sample weights, source-domain ids,
        a synthetic-row mask, and protocol metadata.

    Notes
    -----
    This is a strict source-only Protocol-1 augmentation.  It uses ``X_s``,
    ``y_s``, and source-domain ids only.  No held-out target features or target
    labels are accepted by this API.
    """

    cfg = _coerce_config(config)
    features = _feature_matrix(source_features, name="source_features")
    labels = _label_vector(source_labels, expected_length=features.shape[0], name="source_labels")
    domains = _domain_vector(source_domains, expected_length=features.shape[0])
    unique_domains = tuple(dict.fromkeys(domains.tolist()))
    if len(unique_domains) < 2 and cfg.mixes_per_row > 0:
        raise ValueError("MixStyle source-domain augmentation requires at least two source domains.")
    stats = _domain_stats(features, domains, unique_domains)

    if cfg.mixes_per_row == 0:
        return _original_only_result(features, labels, domains, cfg=cfg, n_domains=len(unique_domains))

    rng = np.random.default_rng(cfg.random_state)
    synthetic_features: list[np.ndarray] = []
    synthetic_labels: list[Any] = []
    synthetic_domains: list[Hashable] = []
    synthetic_lambdas: list[float] = []
    synthetic_partner_domains: list[Hashable] = []

    for row_index, row in enumerate(features):
        own_domain = domains[row_index]
        own_stats = stats[own_domain]
        partner_pool = tuple(domain for domain in unique_domains if domain != own_domain)
        for _ in range(cfg.mixes_per_row):
            partner_domain = partner_pool[int(rng.integers(0, len(partner_pool)))]
            partner_stats = stats[partner_domain]
            lam = float(rng.beta(cfg.alpha, cfg.alpha))
            mixed = mixstyle_row(
                row,
                source_stats=own_stats,
                partner_stats=partner_stats,
                lam=lam,
                style_strength=cfg.style_strength,
            )
            synthetic_features.append(mixed)
            synthetic_labels.append(labels[row_index])
            synthetic_domains.append(own_domain)
            synthetic_lambdas.append(lam)
            synthetic_partner_domains.append(partner_domain)

    synthetic_matrix = np.vstack(synthetic_features).astype(np.float32, copy=False)
    synthetic_label_vector = np.asarray(synthetic_labels, dtype=labels.dtype)
    synthetic_domain_vector = np.asarray(synthetic_domains, dtype=object)
    if cfg.include_original:
        output_features = np.vstack([features, synthetic_matrix]).astype(np.float32, copy=False)
        output_labels = np.concatenate([labels, synthetic_label_vector])
        output_domains = np.concatenate([domains, synthetic_domain_vector])
        synthetic_mask = np.concatenate([np.zeros(features.shape[0], dtype=bool), np.ones(synthetic_matrix.shape[0], dtype=bool)])
        sample_weight = np.concatenate([
            np.ones(features.shape[0], dtype=float),
            np.full(synthetic_matrix.shape[0], float(cfg.synthetic_weight), dtype=float),
        ])
    else:
        output_features = synthetic_matrix
        output_labels = synthetic_label_vector
        output_domains = synthetic_domain_vector
        synthetic_mask = np.ones(synthetic_matrix.shape[0], dtype=bool)
        sample_weight = np.full(synthetic_matrix.shape[0], float(cfg.synthetic_weight), dtype=float)

    metadata = _metadata(
        cfg=cfg,
        n_input_rows=features.shape[0],
        n_output_rows=output_features.shape[0],
        n_synthetic=int(np.count_nonzero(synthetic_mask)),
        n_domains=len(unique_domains),
        feature_dim=features.shape[1],
        synthetic_lambdas=synthetic_lambdas,
        synthetic_partner_domains=synthetic_partner_domains,
    )
    return SourceMixStyleResult(
        features=output_features,
        labels=output_labels,
        sample_weight=sample_weight,
        domain_ids=output_domains,
        synthetic_mask=synthetic_mask,
        metadata=metadata,
    )


def mixstyle_row(
    row: Sequence[float] | np.ndarray,
    *,
    source_stats: Any,
    partner_stats: Any,
    lam: float,
    style_strength: float = DEFAULT_MIXSTYLE_STYLE_STRENGTH,
) -> np.ndarray:
    """Transform one feature row with mixed source-domain style statistics."""

    vector = np.asarray(row, dtype=float).reshape(-1)
    if vector.ndim != 1 or vector.size < 1:
        raise ValueError("row must be a one-dimensional feature vector.")
    lam = _normalize_unit_interval(lam, name="lam")
    style_strength = _normalize_unit_interval(style_strength, name="style_strength")
    source = _coerce_stats(source_stats, expected_width=vector.shape[0], name="source_stats")
    partner = _coerce_stats(partner_stats, expected_width=vector.shape[0], name="partner_stats")
    mixed_mean = lam * source.mean + (1.0 - lam) * partner.mean
    mixed_scale = lam * source.scale + (1.0 - lam) * partner.scale
    standardized = (vector - source.mean) / source.scale
    styled = standardized * mixed_scale + mixed_mean
    return ((1.0 - style_strength) * vector + style_strength * styled).astype(np.float32, copy=False)


def _coerce_config(config: SourceMixStyleConfig | Mapping[str, Any] | None) -> SourceMixStyleConfig:
    if config is None:
        return source_mixstyle_config()
    if isinstance(config, SourceMixStyleConfig):
        return config
    return source_mixstyle_config(**dict(config))


def _domain_stats(features: np.ndarray, domains: np.ndarray, unique_domains: Sequence[Hashable]) -> dict[Hashable, _DomainStyleStats]:
    stats: dict[Hashable, _DomainStyleStats] = {}
    for domain in unique_domains:
        domain_features = features[domains == domain]
        if domain_features.shape[0] < 1:
            raise ValueError(f"Source domain {domain!r} has no rows.")
        mean = np.mean(domain_features, axis=0)
        scale = np.std(domain_features, axis=0, ddof=0)
        scale = np.maximum(scale, _MIN_SCALE)
        stats[domain] = _DomainStyleStats(domain_id=domain, mean=mean, scale=scale, n_rows=domain_features.shape[0])
    return stats


def _coerce_stats(value: Any, *, expected_width: int, name: str) -> _DomainStyleStats:
    if isinstance(value, _DomainStyleStats):
        stats = value
    elif isinstance(value, Mapping):
        stats = _DomainStyleStats(
            domain_id=value.get("domain_id", name),
            mean=np.asarray(value["mean"], dtype=float).reshape(-1),
            scale=np.asarray(value["scale"], dtype=float).reshape(-1),
            n_rows=int(value.get("n_rows", 0)),
        )
    else:
        raise ValueError(f"{name} must be a domain-style stats object or mapping with mean and scale.")
    if stats.mean.shape[0] != expected_width or stats.scale.shape[0] != expected_width:
        raise ValueError(f"{name} mean/scale width must match row width {expected_width}.")
    if not np.all(np.isfinite(stats.mean)) or not np.all(np.isfinite(stats.scale)) or np.any(stats.scale <= 0.0):
        raise ValueError(f"{name} mean and scale must be finite, with positive scale entries.")
    return stats


def _original_only_result(features: np.ndarray, labels: np.ndarray, domains: np.ndarray, *, cfg: SourceMixStyleConfig, n_domains: int) -> SourceMixStyleResult:
    metadata = _metadata(
        cfg=cfg,
        n_input_rows=features.shape[0],
        n_output_rows=features.shape[0],
        n_synthetic=0,
        n_domains=n_domains,
        feature_dim=features.shape[1],
        synthetic_lambdas=[],
        synthetic_partner_domains=[],
    )
    return SourceMixStyleResult(
        features=features.astype(np.float32, copy=False),
        labels=labels.copy(),
        sample_weight=np.ones(features.shape[0], dtype=float),
        domain_ids=domains.copy(),
        synthetic_mask=np.zeros(features.shape[0], dtype=bool),
        metadata=metadata,
    )


def _metadata(
    *,
    cfg: SourceMixStyleConfig,
    n_input_rows: int,
    n_output_rows: int,
    n_synthetic: int,
    n_domains: int,
    feature_dim: int,
    synthetic_lambdas: Sequence[float],
    synthetic_partner_domains: Sequence[Hashable],
) -> dict[str, Any]:
    lambdas = np.asarray(synthetic_lambdas, dtype=float)
    return {
        "source_mixstyle": True,
        "source_mixstyle_protocol": SOURCE_MIXSTYLE_PROTOCOL,
        "source_mixstyle_protocol_category": SOURCE_MIXSTYLE_CATEGORY,
        "source_mixstyle_uses_source_features": True,
        "source_mixstyle_uses_source_labels": True,
        "source_mixstyle_uses_source_domains": True,
        "source_mixstyle_uses_target_features": False,
        "source_mixstyle_uses_target_labels": False,
        "source_mixstyle_valid_for_strict_source_only": True,
        "source_mixstyle_valid_for_unlabeled_target_adaptation": True,
        "source_mixstyle_valid_for_target_calibration": False,
        "source_mixstyle_n_input_rows": int(n_input_rows),
        "source_mixstyle_n_output_rows": int(n_output_rows),
        "source_mixstyle_n_synthetic_rows": int(n_synthetic),
        "source_mixstyle_n_source_domains": int(n_domains),
        "source_mixstyle_feature_dim": int(feature_dim),
        "source_mixstyle_mixes_per_row": int(cfg.mixes_per_row),
        "source_mixstyle_alpha": float(cfg.alpha),
        "source_mixstyle_style_strength": float(cfg.style_strength),
        "source_mixstyle_synthetic_weight": float(cfg.synthetic_weight),
        "source_mixstyle_include_original": bool(cfg.include_original),
        "source_mixstyle_random_state": "" if cfg.random_state is None else int(cfg.random_state),
        "source_mixstyle_lambda_mean": "" if lambdas.size == 0 else float(np.mean(lambdas)),
        "source_mixstyle_lambda_min": "" if lambdas.size == 0 else float(np.min(lambdas)),
        "source_mixstyle_lambda_max": "" if lambdas.size == 0 else float(np.max(lambdas)),
        "source_mixstyle_partner_domain_preview": "|".join(str(domain) for domain in synthetic_partner_domains[:12]),
    }


def _feature_matrix(values: Sequence[Sequence[float]] | np.ndarray, *, name: str) -> np.ndarray:
    matrix = np.asarray(values, dtype=float)
    if matrix.ndim != 2:
        raise ValueError(f"{name} must be a two-dimensional feature matrix.")
    if matrix.shape[0] < 1 or matrix.shape[1] < 1:
        raise ValueError(f"{name} must contain at least one row and one feature column.")
    if not np.all(np.isfinite(matrix)):
        raise ValueError(f"{name} must contain only finite values.")
    return matrix


def _label_vector(values: Sequence[Any] | np.ndarray, *, expected_length: int, name: str) -> np.ndarray:
    vector = np.asarray(values).reshape(-1)
    if vector.shape[0] != expected_length:
        raise ValueError(f"{name} must contain one value per source row: {vector.shape[0]} != {expected_length}.")
    return vector


def _domain_vector(values: Sequence[Hashable] | np.ndarray, *, expected_length: int) -> np.ndarray:
    vector = np.asarray(values, dtype=object).reshape(-1)
    if vector.shape[0] != expected_length:
        raise ValueError(f"source_domains must contain one value per source row: {vector.shape[0]} != {expected_length}.")
    for domain in vector.tolist():
        try:
            hash(domain)
        except TypeError as exc:
            raise ValueError(f"source_domains must be hashable; got {domain!r}.") from exc
    return vector


def _normalize_nonnegative_int(value: int | str, *, name: str) -> int:
    if isinstance(value, (bool, np.bool_)):
        raise ValueError(f"{name} must be a non-negative integer.")
    try:
        parsed = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be a non-negative integer.") from exc
    if not np.isfinite(parsed) or parsed % 1.0 != 0.0 or parsed < 0:
        raise ValueError(f"{name} must be a non-negative integer.")
    return int(parsed)


def _normalize_positive_float(value: float | str, *, name: str) -> float:
    if isinstance(value, (bool, np.bool_)):
        raise ValueError(f"{name} must be a positive finite value.")
    try:
        parsed = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be a positive finite value.") from exc
    if not np.isfinite(parsed) or parsed <= 0.0:
        raise ValueError(f"{name} must be a positive finite value.")
    return parsed


def _normalize_nonnegative_float(value: float | str, *, name: str) -> float:
    if isinstance(value, (bool, np.bool_)):
        raise ValueError(f"{name} must be finite and non-negative.")
    try:
        parsed = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be finite and non-negative.") from exc
    if not np.isfinite(parsed) or parsed < 0.0:
        raise ValueError(f"{name} must be finite and non-negative.")
    return parsed


def _normalize_unit_interval(value: float | str, *, name: str) -> float:
    if isinstance(value, (bool, np.bool_)):
        raise ValueError(f"{name} must be in [0, 1].")
    try:
        parsed = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be in [0, 1].") from exc
    if not np.isfinite(parsed) or parsed < 0.0 or parsed > 1.0:
        raise ValueError(f"{name} must be in [0, 1].")
    return parsed
